#!/bin/bash

url="$1"

function getVersion () {
  echo "$1" | sed 's/^.*\///;s/[^.0-9]//g;s/[.]*/ /g;s/^ *//;s/ *$//;s/ /./g'
}

ver=$(getVersion "$url")

if ! [ "$ver" ]; then
  echo "Could not determine version from '$url'"
  exit 1
fi

mkdir -p versions
cd versions

if [ -e "$ver" ]; then
  echo "Cowardly refusing to step on existing file or dir '$ver'"
  exit 2
fi

mkdir $ver
cd $ver
wget "$url"
unzip *.zip
media=*/media
swf=*/BreedingSeason*.swf

if ! [ -d $media ]; then
  echo "$media doesn't exist or isn't a directory."
  exit 3
fi

if ! [ -f $swf ]; then
  echo "$swf doesn't exist or isn't a file."
  exit 4
fi

ln -s $media
ln -s $swf BreedingSeason.swf
cd ..

echo "Switching current version from '$(readlink current)' to $ver"
rm -f current
ln -s $ver current
