#!/bin/bash

if false; then
  . ~/.lib/util

  LOG=$(startLog initAgent)

  function log() { echo "$@" >> $LOG; }

  agentInfo="$HOME/.ssh/agent.info"

  function agentInfoSame() {
    if !  [ -e $agentInfo ]; then
      log "no $agentInfo, so agentInfoSame is false"
      return 1
    fi

    # Tragically, diff's result answers "are they the same", rather than "is there a difference"
    diff -q $agentInfo <(set | grep ^SSH) > /dev/null 2>&1
    ret=$?
    log "agentInfoSame says $ret"
    return $ret
  }

  function agentPID() {
    echo $SSH_AUTH_SOCK | sed 's/.*agent.//'
  }

  function testAgent() {
    [    "$SSH_AUTH_SOCK" ]                  &&
    [ -e "$SSH_AUTH_SOCK" ]                  &&
    ps -p "$(agentPID)"     > /dev/null 2>&1 &&
    timeout 5 ssh-add -l    > /dev/null 2>&1
    ret=$?
    log "testAgent: $ret"
    return $ret
  }

  function findAgent() {
    testAgent
    ret=$?

    if [ $ret == 0 ]; then
      return
    elif agentInfoSame; then
      log "agent dead and no new agentInfo found"
      return $ret
    fi

    source $agentInfo
    testAgent
    return $?
  }

  findAgent
  ret=$?

  if [ $ret -eq 124 ]; then
    echo 'Agent death upstream? Maybe look into it?'
  fi

  if [ $ret -lt 1 ]; then
    if ! agentInfoSame; then
      set | grep ^SSH > $agentInfo
      log 'Saved working env'
    fi
  else
    echo "Lost connection to laptop ssh agent."
  fi

fi
