#!/bin/bash

ws-setup () {
  cd ~/ws
  setup-ws $1
  cd $1/src/$1
}

flowBalancerCLI () {
  cd ~/ws/FlowBalancerCLI/src/FlowBalancerCLI
  brazil-build run-cli -Dargs="$*"
}

show-path() {
  echo $PATH | sed 's/:/\n/g'
}

odin-add() {
  if [ -n "$1" ]; then
    /apollo/env/OdinTools/bin/odin adminapi --AddHost -n "$1" -h DEV-DSK-$(whoami | tr a-z A-Z)/HostClass
  else
    echo "Usage: odin-add <material-set>"
  fi
}

makeme() {
  if [ "$1" ]; then
    source <(
      odin-get "$1" | (
        read AKI
        read ASK
        echo export AWS_ACCESS_KEY_ID=$AKI
        echo export AWS_SECRET_ACCESS_KEY=$ASK
      )
    )
    echo Using key $AWS_ACCESS_KEY_ID
  else
    echo "Usage: makeme <material-set>"
  fi
}

timber () {
  if [ ! "$1" ]; then
    echo "Usage: timber <env>"
  else
    sshenv TimberFS/$1/Lookout
  fi
}

