#!/bin/bash

if hostname | grep -q $USER; then
  if [ "$STY" ]; then
    where=$(pwd | sed 's/\/home\/forestr/~/')
    retitle $where
  fi

  # Must source to get SSH vars exported
  source $HOME/.lib/initAgent

  ~/bin/refresh-kerberos-ticket

  fixedPwd="$(pwd | sed 's/^\/local\/home/\/home/;s/ws\/ForestrHome//')"
  if [ "${PWD}" != "$fixedPwd" ]; then
    cd - > /dev/null 2>&1
    cd "$fixedPwd"
  fi
fi
