#!/bin/bash

startLog () {
  file=${1:-default}
  daysKept=${2:-14}

  find ~/.log -name $file -mtime +$daysKept -exec rm '{}' ';'
  rmdir ~/.log/* 2> /dev/null

  dir=~/.log/$$
  mkdir -p $dir

  echo "$dir/$file"
}

export startLog
