fs        = require 'fs'
path      = require 'path'

{ find }  = require './lib/find'

setup     = require './lib/setup-testing'

task "test", ->
  require './test'

task "test::coverage", ->
  process.chdir 'lib'

  try
    missing = []

    coffeeSuffix = ({fileName}) -> fileName.endsWith 'coffee'
    noteMissingTest = (info) ->
      {relativePath} = info

      if not (fs.stat testPath = path.resolve '..', 'test', relativePath).isFile()
        missing.push testPath

    find predicate: coffeeSuffix, receiver: noteMissingTest

  finally
    process.chdir '..'
