// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(Item) {
    Item.prototype.due = function() {
      return !this.acknowledged || (this.acknowledged + this.schedule().interval < Date.now());
    };
    Item.prototype.acknowledge = function(cb) {
      this.acknowledged = Date.now();
      this.save();
      return cb(null);
    };
    return Item.remoteMethod('acknowledge', {
      isStatic: false,
      description: 'Snooze an item'
    });
  };

}).call(this);
