// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(Participant) {
    Participant.prototype.pendingMessages = function(cb) {
      return cb(null, this.items().filter(function(i) {
        return i.due();
      }));
    };
    return Participant.remoteMethod('pendingMessages', {
      isStatic: false,
      returns: {
        arg: 'items',
        type: 'array'
      }
    });
  };

}).call(this);
