// Generated by CoffeeScript 1.10.0
var slice = [].slice;

define([], function() {
  var Common;
  Common = {
    TodoFilter: '',
    ENTER_KEY: 13,
    ESCAPE_KEY: 27,
    apiUrl: '/api/v1',
    api: function() {
      var parts;
      parts = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return [Common.apiUrl].concat(slice.call(parts)).join('/');
    }
  };
  return Object.defineProperty(Common, 'session', {
    get: function() {
      return JSON.parse(localStorage.getItem('sessionKey'));
    },
    set: function(id) {
      return localStorage.setItem('sessionKey', JSON.stringify(id));
    }
  });
});
