// Generated by CoffeeScript 1.10.0
var slice = [].slice;

define(['jquery', 'common', 'jquery-ui'], function($, Common) {
  var fields, loginUser, logoutUser, registerUser, validateSession;
  fields = function() {
    var el, i, key, keys, len, ret;
    keys = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    ret = {};
    for (i = 0, len = keys.length; i < len; i++) {
      key = keys[i];
      el = $("#" + key)[0];
      ret[el.id] = el.value;
    }
    return ret;
  };
  validateSession = function(session) {
    return $.ajax({
      type: "GET",
      url: Common.api('Participants', session.userId),
      headers: {
        Authorization: session.id
      }
    }).done(function(user, result, response) {
      var field, i, len, ref;
      console.log("Validate result: ", arguments);
      ref = ['goal', 'username', 'email'];
      for (i = 0, len = ref.length; i < len; i++) {
        field = ref[i];
        $("#" + field).val(user[field]);
      }
      return $("#logout").button('enable');
    });
  };
  logoutUser = function() {
    return $.ajax({
      type: "POST",
      url: Common.api('Participants', 'logout'),
      headers: {
        Authorization: Common.session.id
      }
    }).done(function(o, result, response) {
      return console.log("Logout result: ", arguments);
    });
  };
  loginUser = function(user) {
    var url;
    if (user == null) {
      user = fields('username', 'password');
    }
    url = Common.api('Participants', 'login');
    return $.ajax({
      type: "POST",
      url: url,
      data: user
    }).done(function(session, result, response) {
      console.log("Login result: ", arguments);
      if (result === "success") {
        Common.session = session;
        $("#logout").button('enable');
        return $("#login, #register").button('disable');
      }
    });
  };
  registerUser = function() {
    var form, url;
    url = Common.api('Participants');
    form = fields('goal', 'username', 'password', 'email');
    return $.ajax({
      type: "POST",
      url: url,
      data: form
    }).done(function(user, result, response) {
      var password, username;
      console.log("Register result: ", arguments);
      if (result === "success") {
        username = form.username, password = form.password;
        return loginUser({
          username: username,
          password: password
        });
      }
    });
  };
  $("#logout").button().button('disable').click(function(e) {
    e.preventDefault();
    return logoutUser();
  });
  $("#login").button().click(function(e) {
    e.preventDefault();
    return loginUser();
  });
  $("#passconf").keyup(function(e) {
    if (this.value !== $("#password")[0].value) {
      return $("#register").button('disable');
    } else {
      return $("#register").button('enable');
    }
  });
  $("#register").button().click(function(e) {
    e.preventDefault();
    return registerUser();
  });
  return validateSession(Common.session);
});
