// Generated by CoffeeScript 1.9.3
(function() {
  var Path,
    slice = [].slice;

  module.exports = Path = (function() {
    function Path() {
      var maze, steps;
      maze = arguments[0], steps = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      this.maze = maze;
      this.steps = steps;
      Object.defineProperties(this, {
        start: {
          get: function() {
            return this.steps[0];
          }
        },
        rest: {
          get: function() {
            return this.steps.slice(1);
          }
        },
        end: {
          get: function() {
            return this.steps[this.steps.length(-1)];
          }
        }
      });
    }

    Path.prototype.length = function() {
      return this.steps.length;
    };

    Path.prototype.connected = function(pinOrPath) {
      return this.map === pin.map && this.end.pin === pin.pin;
    };

    Path.prototype.toString = function() {
      return (this.maze + ": [") + this.steps.map(function(s) {
        return s.toString();
      }).join(", ") + "]";
    };

    return Path;

  })();

}).call(this);
