#!/usr/bin/env coffee

{ argv } = require 'process'
{ option, processArgv } = require 'rdf/lib/shell'

{option, processArgv} = do ->
  optionDefinitions = {}

  option: (letter, name, expectations = Expect.increments) ->


main = ->
  { opts, remaining } = processArgv argv

processArgv = (argv, optDef) ->

  for arg, i in argv
