// ==UserScript==
// @name         Lil' Alchemist assistant
// @namespace    http://thatsnice.org/
// @version      0.1
// @description  Remember cards held, decks organized, make recommendations
// @author       Robert de Forest <guitar.robot@gmail.com>
// @match        http://lil-alchemist.wikia.com/wiki/*
// @grant        none
// @require      http://coffeescript.org/extras/coffee-script.js
// ==/UserScript==

var inline_src = (<><![CDATA[
// Generated by CoffeeScript 1.10.0
var cardLinks, linkIntensifies, revealMenu, ss, styleSheet;

$(document.head).append($("<style>"));

ss = document.styleSheets;

styleSheet = ss[ss.length - 1];

styleSheet.insertRule("div.intensified {\n  border: solid black 1px;\n}");

cardLinks = function() {
  return $('.article-table a').filter(function(idx, el) {
    var cardName, href;
    href = $(el).attr('href');
    cardName = el.innerText;
    return href === '/wiki/' + cardName.replace(" ", "_");
  });
};

$("span.mw-headline span.button").each(function(i, e) {
  return e.click();
});

revealMenu = function(div) {
  console.log("Release the kracken");
  return console.log(div);
};

linkIntensifies = function(el) {
  var div;
  $(el.parentElement).append(div = $("<div>"));
  div.append(el);
  div.on('mouseEnter', function() {
    return revealMenu(div);
  });
  return div.addClass('intensified');
};

cardLinks().each(function(idx, el) {
  return linkIntensifies(el);
});

window.laa = {
  cardLinks: cardLinks,
  revealMenu: revealMenu,
  linkIntensifies: linkIntensifies,
  styleSheet: styleSheet
};
]]></>).toString();
var compiled = this.CoffeeScript.compile(inline_src);
eval(compiled);
